/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_categories__get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_categories__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Category */
        get: operations["get_category_categories__category_id__get"];
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_categories__category_id__patch"];
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_users__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Expenses */
        get: operations["list_user_expenses_expenses__get"];
        put?: never;
        /** Create Expense */
        post: operations["create_expense_expenses__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Expense */
        get: operations["get_expense_expenses__expense_id__get"];
        put?: never;
        post?: never;
        /** Delete Expense */
        delete: operations["delete_expense_expenses__expense_id__delete"];
        options?: never;
        head?: never;
        /** Update Expense */
        patch: operations["update_expense_expenses__expense_id__patch"];
        trace?: never;
    };
    "/expenses/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Expenses */
        get: operations["list_all_expenses_expenses_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incomes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Incomes */
        get: operations["list_user_incomes_incomes__get"];
        put?: never;
        /** Create Income */
        post: operations["create_income_incomes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incomes/{income_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Income */
        get: operations["get_income_incomes__income_id__get"];
        put?: never;
        post?: never;
        /** Delete Income */
        delete: operations["delete_income_incomes__income_id__delete"];
        options?: never;
        head?: never;
        /** Update Income */
        patch: operations["update_income_incomes__income_id__patch"];
        trace?: never;
    };
    "/incomes/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Incomes */
        get: operations["list_all_incomes_incomes_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_dashboard__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            kind: components["schemas"]["CategoryKind"];
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
        };
        /**
         * CategoryKind
         * @enum {string}
         */
        CategoryKind: "income" | "expense";
        /** CategoryRead */
        CategoryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string | null;
            /** Name */
            name: string;
            kind: components["schemas"]["CategoryKind"];
            /** Color */
            color: string | null;
            /** Icon */
            icon: string | null;
            /** Sort Order */
            sort_order: number;
            /** Is Default */
            is_default: boolean;
            /** Is Archived */
            is_archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            kind?: components["schemas"]["CategoryKind"] | null;
            /** Color */
            color?: string | null;
            /** Icon */
            icon?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /** DashboardRead */
        DashboardRead: {
            /** Total Incomes */
            total_incomes: string;
            /** Total Expenses */
            total_expenses: string;
            /** Total Balance */
            total_balance: string;
            /** Total Fixed Expenses */
            total_fixed_expenses: string;
            /** Total Automatic Expenses */
            total_automatic_expenses: string;
            /** Total Installment Expenses */
            total_installment_expenses: string;
            /** Total One Time Expenses */
            total_one_time_expenses: string;
            /** Total Recurring Incomes */
            total_recurring_incomes: string;
            /** Total One Time Incomes */
            total_one_time_incomes: string;
        };
        /** ExpenseCreate */
        ExpenseCreate: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Amount */
            amount: number | string;
            expense_type: components["schemas"]["ExpenseType"];
            /** Purchase Date */
            purchase_date?: string | null;
            /**
             * Impact Start Date
             * Format: date
             */
            impact_start_date: string;
            /** Impact End Date */
            impact_end_date?: string | null;
            /**
             * Installments Count
             * @default 1
             */
            installments_count: number;
            /** Source Text */
            source_text?: string | null;
        };
        /** ExpenseRead */
        ExpenseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Category Id */
            category_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            expense_type: components["schemas"]["ExpenseType"];
            /** Purchase Date */
            purchase_date: string | null;
            /**
             * Impact Start Date
             * Format: date
             */
            impact_start_date: string;
            /** Impact End Date */
            impact_end_date: string | null;
            /** Installments Count */
            installments_count: number | null;
            /** Source Text */
            source_text: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ExpenseType
         * @enum {string}
         */
        ExpenseType: "one_time" | "automatic_debit" | "fixed" | "installment";
        /** ExpenseUpdate */
        ExpenseUpdate: {
            /** Category Id */
            category_id?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Amount */
            amount?: number | string | null;
            expense_type?: components["schemas"]["ExpenseType"] | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Impact Start Date */
            impact_start_date?: string | null;
            /** Impact End Date */
            impact_end_date?: string | null;
            /** Installments Count */
            installments_count?: number | null;
            /** Source Text */
            source_text?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncomeCreate */
        IncomeCreate: {
            /**
             * Category Id
             * Format: uuid
             */
            category_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Amount */
            amount: number | string;
            income_type: components["schemas"]["IncomeType"];
            /** Received Date */
            received_date?: string | null;
            /**
             * Impact Start Date
             * Format: date
             */
            impact_start_date: string;
            /** Impact End Date */
            impact_end_date?: string | null;
            /** Source Text */
            source_text?: string | null;
        };
        /** IncomeRead */
        IncomeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Category Id */
            category_id: string | null;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Amount */
            amount: string;
            income_type: components["schemas"]["IncomeType"];
            /** Received Date */
            received_date: string | null;
            /**
             * Impact Start Date
             * Format: date
             */
            impact_start_date: string;
            /** Impact End Date */
            impact_end_date: string | null;
            /** Source Text */
            source_text: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IncomeType
         * @enum {string}
         */
        IncomeType: "one_time" | "recurring";
        /** IncomeUpdate */
        IncomeUpdate: {
            /** Category Id */
            category_id?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Amount */
            amount?: number | string | null;
            income_type?: components["schemas"]["IncomeType"] | null;
            /** Received Date */
            received_date?: string | null;
            /** Impact Start Date */
            impact_start_date?: string | null;
            /** Impact End Date */
            impact_end_date?: string | null;
            /** Source Text */
            source_text?: string | null;
        };
        /** RawListResponse[CategoryRead] */
        RawListResponse_CategoryRead_: {
            /** Data */
            data: components["schemas"]["CategoryRead"][];
            /** Total */
            total: number;
        };
        /** RawListResponse[ExpenseRead] */
        RawListResponse_ExpenseRead_: {
            /** Data */
            data: components["schemas"]["ExpenseRead"][];
            /** Total */
            total: number;
        };
        /** RawListResponse[IncomeRead] */
        RawListResponse_IncomeRead_: {
            /** Data */
            data: components["schemas"]["IncomeRead"][];
            /** Total */
            total: number;
        };
        /** RawListResponse[UserRead] */
        RawListResponse_UserRead_: {
            /** Data */
            data: components["schemas"]["UserRead"][];
            /** Total */
            total: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_categories_categories__get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["CategoryKind"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawListResponse_CategoryRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_category_categories__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_category_categories__category_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawListResponse_UserRead_"];
                };
            };
        };
    };
    list_user_expenses_expenses__get: {
        parameters: {
            query?: {
                category_id?: string | null;
                title?: string | null;
                amount_gte?: number | string | null;
                amount_lte?: number | string | null;
                expense_type?: components["schemas"]["ExpenseType"] | null;
                purchase_date_gte?: string | null;
                purchase_date_lte?: string | null;
                impact_start_date_gte?: string | null;
                impact_start_date_lte?: string | null;
                impact_end_date_gte?: string | null;
                impact_end_date_lte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawListResponse_ExpenseRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_expense_expenses__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_expense_expenses__expense_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_expense_expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_expense_expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_expenses_expenses_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawListResponse_ExpenseRead_"];
                };
            };
        };
    };
    list_user_incomes_incomes__get: {
        parameters: {
            query?: {
                category_id?: string | null;
                title?: string | null;
                amount_gte?: number | string | null;
                amount_lte?: number | string | null;
                expense_type?: components["schemas"]["IncomeType"] | null;
                purchase_date_gte?: string | null;
                purchase_date_lte?: string | null;
                impact_start_date_gte?: string | null;
                impact_start_date_lte?: string | null;
                impact_end_date_gte?: string | null;
                impact_end_date_lte?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawListResponse_IncomeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_income_incomes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_income_incomes__income_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_income_incomes__income_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_income_incomes__income_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                income_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncomeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_incomes_incomes_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawListResponse_IncomeRead_"];
                };
            };
        };
    };
    get_dashboard_dashboard__get: {
        parameters: {
            query?: {
                period_start?: string | null;
                period_end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
